actions:
  flake8:
    include: "*.py"
    exclude: "docs/*.py"
    run: flake8 {files}
  shellcheck:
    include:
      - "*.sh"
      - pre-commit-template
    run: shellcheck {files}
shortcuts:
  lint:
    flags:
      - use-git
      - include-unstaged
      - include-untracked
  "lint:all":
    extends: lint
    flags: use-tracked-files
  fix:
    extends: lint
    flags: fix
  "fix:all":
    extends: fix
    flags: use-tracked-files
