sudo: false
language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
cache: pip
install:
  - pip install --upgrade pip
  - pip install flake8 tox-travis .
script:
  - therapist run --use-tracked-files
  - tox
