sudo: false
language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
install: pip install flake8 tox-travis .
script:
  - therapist run --use-tracked-files
  - tox
