version: 2
jobs:
  test: &test-defaults
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - run:
          name: Install shellcheck
          command: |
            sudo apt-get update
            sudo apt-get install shellcheck

      - restore_cache:
          key: v1-python-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Create virtualenv
          command: |
            mkdir -p ~/.venv
            virtualenv ~/.venv
            echo "source ~/.venv/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements-dev.txt
            pip install .

      - save_cache:
          paths:
            - "~/.venv"
          key: v1-python-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Lint
          command: therapist run --use-tracked-files

      - run:
          name: Test
          command: py.test

  test-py27:
    <<: *test-defaults
    docker:
      - image: circleci/python:2.7

  test-py34:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.4

  test-py35:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.5

  test-py36:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.6

  test-py37:
    <<: *test-defaults
    docker:
      - image: circleci/python:3.7

  deploy:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - restore_cache:
          key: v1-python-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Create virtualenv
          command: |
            mkdir -p ~/.venv
            virtualenv ~/.venv
            echo "source ~/.venv/bin/activate" >> $BASH_ENV
      
      - run:
          name: Install dependencies
          command: pip install twine

      - save_cache:
          paths:
            - "~/.venv"
          key: v1-python-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Verify git tag matches version
          command: python setup.py verify

      - run:
          name: Create .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = rehandalal" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Create distributions
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      
      - run:
          name: Upload to PyPI
          command: twine upload dist/*

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-py27:
          filters:
            tags:
              only: /^v.*/
      - test-py34:
          filters:
            tags:
              only: /^v.*/
      - test-py35:
          filters:
            tags:
              only: /^v.*/
      - test-py36:
          filters:
            tags:
              only: /^v.*/
      - test-py37:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test-py27
            - test-py34
            - test-py35
            - test-py36
            - test-py37
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
