#!/usr/bin/env bash
# THERAPIST %hash%

exitcode=0

# Get the current working directory
pushd "$(dirname "$0")" > /dev/null
CWD=$(pwd)
popd > /dev/null

# Run the legacy pre-commit if it exists
if [ -x "$CWD"/pre-commit.legacy ]; then
    if ! "$CWD"/pre-commit.legacy; then
        exitcode=1
    fi
fi

if ! %therapist_bin% run; then
    exitcode=1
fi

exit ${exitcode}
