#!/usr/bin/env python
import os
import subprocess
import yaml

from distutils.spawn import find_executable

from therapist import Runner
from therapist.printer import Printer

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GIT_BINARY = find_executable('git')

# Get a list of the modified tracked files
status = subprocess.check_output([GIT_BINARY, 'status', '--porcelain', '-uno'])

files = []

for line in status.splitlines():
    state = line[1]
    if state != 'M':
        files.append(line[3:])

if files:
    # Try and load the config file
    try:
        with open(os.path.join(BASE_DIR, 'therapist.yml'), 'r') as config_file:
            config = yaml.safe_load(config_file)
    except IOError:
        printer = Printer()
        printer.fprint('ERROR: Missing configuration file.', 'red', 'bold')
        printer.fprint('You must create a `therapist.yml` file or use the --no-verify option.', 'red', 'bold')
        exit(1)
    else:
        # Change the current directory to the base directory
        os.chdir(BASE_DIR)

        # Run the commands
        runner = Runner(config)
        runner.run()
